alunos_matematica = []
alunos_contabilidade = []

for aluno in (alunos_matematica): 
    print("quantidaes de alunos")

lista = 0
while lista<150:
    numero = alunos_matematicatica = int(input('entre com num, da matr,pra matematica, ou 0 pra sair: '))
    if numero[lista] == 0: break
lista = lista + 1
alunos_matematica.append(numero)
print('as matriculas de alunos_matematica 1 são : ', alunos_matematica)






    




